name: Test and coverage

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-go@main
        with:
          go-version: 'stable'

      - name: Run Tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Print coverage
        run: go tool cover -func=coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@main
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Cache SonarCloud packages
        uses: actions/cache@main
        with:
          path: /opt/sonar-scanner/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}